### PR TITLE
SCMOD-5452: ready for release

### PR DESCRIPTION
**Pull request by rahul-kulkarni73**
Nothing to be added to release notes

### CODE REVIEW

**Review by davidegph — APPROVED** [review]
All fine.

**Review by michael-bryson — CHANGES_REQUESTED** [review]
There is no information added to the release notes at all. You need to add any new features or known issues etc before this can released.

**Comment by rahul-kulkarni73** [comment]
Don't see any info worth mentioning. Don't see any bigger change since last release.

**Comment by michael-bryson** [comment]
We can't leave release notes empty, if we are releasing a component there needs to be a reason for it. I found this for example:
- https://autjira.microfocus.com/browse/SCMOD-4898 - Configuration option has been added so that the worker will no longer send job tracking updates

**Comment by rahul-kulkarni73** [comment]
The problem is that tkt is change in worker framework and nothing changed in lang detect. So cannot add the change here. Let me add it as it cannot be left blank then.

**Comment by michael-bryson** [comment]
I know that change is in worker-framework but the change has added a feature to worker-languagedetection so it can and should be added here.

**Comment by rahul-kulkarni73** [comment]
I think in this case since we don't have anything we can put this down. But list of changes in base project cannot be listed in the downstream projects.

**Comment by michael-bryson** [comment]
You are correct that we do not list changes in base projects. However this change exposes an option that may be of use in this release. This is not the same as a change in a base project, it provides an option that affects the behaviour of this worker and as such should be listed. In this case it should be listed as a feature as the default behaviour has not changed, if for example the default behaviour had changed then this would need listed as a breaking change.

**Comment by rahul-kulkarni73** [comment]
Oh didn't see the setting that needs to go on to each worker. Thanks. Maybe we need to add this feature to other workers as well then.

**Comment by michael-bryson** [comment]
Yes, I have added a comment to all the relevant release JIRA to make sure it is added to the release notes of each of them.

**Comment by rahul-kulkarni73** [comment]
Changes done.

**Pull request merged**
